config/routes.rb
Rails.application.routes.draw do
  resources :acct_types

  resources :acct_transactions

  resources :addresses

  get 'home/index'
  get 'home/about'
  root 'home#index'

  resources :account_types, :accounts, :administrators, :customers, :roles, :states, :transaction_types, :transactions, :users, :zip_codes

end

app/models/account.rb
class Account < ActiveRecord::Base
	# self.primary_key = "id"

	has_one :customer
	has_one :account_type
	has_many :acct_transactions
end

app/models/acct_transaction.rb
class AcctTransaction < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :account
	has_one :transaction_type
end

app/models/acct_type.rb
class AcctType < ActiveRecord::Base
	belongs_to :account
end

app/models/address.rb
class Address < ActiveRecord::Base
	# self.primary_key = "customer_id"
	
	belongs_to :customer
	has_one :zip_code
	has_one :state, through: :zip_code
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :user
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :user
	has_one :address
	has_many :accounts
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :zip_code
end

app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
	belongs_to :transactions
end

app/models/user.rb
class User < ActiveRecord::Base
	# self.primary_key = "id"

	# has_one :role
	has_many :customers
	has_many :administrators
end

app/models/zip_code.rb
class ZipCode < ActiveRecord::Base
	# self.primary_key = "zip_code"
	
	has_one :state
	belongs_to :address
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end
end

app/controllers/transaction_types_controller.rb
class TransactionTypesController < ApplicationController
  before_action :set_transaction_type, only: [:show, :edit, :update, :destroy]

  # GET /transaction_types
  # GET /transaction_types.json
  def index
    @transaction_types = TransactionType.all
  end

  # GET /transaction_types/1
  # GET /transaction_types/1.json
  def show
  end

  # GET /transaction_types/new
  def new
    @transaction_type = TransactionType.new
  end

  # GET /transaction_types/1/edit
  def edit
  end

  # POST /transaction_types
  # POST /transaction_types.json
  def create
    @transaction_type = TransactionType.new(transaction_type_params)

    respond_to do |format|
      if @transaction_type.save
        format.html { redirect_to @transaction_type, notice: 'Transaction type was successfully created.' }
        format.json { render :show, status: :created, location: @transaction_type }
      else
        format.html { render :new }
        format.json { render json: @transaction_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_types/1
  # PATCH/PUT /transaction_types/1.json
  def update
    respond_to do |format|
      if @transaction_type.update(transaction_type_params)
        format.html { redirect_to @transaction_type, notice: 'Transaction type was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_type }
      else
        format.html { render :edit }
        format.json { render json: @transaction_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_types/1
  # DELETE /transaction_types/1.json
  def destroy
    @transaction_type.destroy
    respond_to do |format|
      format.html { redirect_to transaction_types_url, notice: 'Transaction type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_type
      @transaction_type = TransactionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_type_params
      params[:transaction_type]
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/acct_types_helper.rb
module AcctTypesHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/transaction_types_helper.rb
module TransactionTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

app/views/transaction_types/_form.html.erb
<%= form_for(@transaction_type) do |f| %>
  <% if @transaction_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction_type.errors.count, "error") %> prohibited this transaction_type from being saved:</h2>

      <ul>
      <% @transaction_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_types/edit.html.erb
<h1>Editing transaction_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction_type %> |
<%= link_to 'Back', transaction_types_path %>

app/views/transaction_types/index.html.erb
<h1>Listing transaction_types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_types.each do |transaction_type| %>
      <tr>
        <td><%= link_to 'Show', transaction_type %></td>
        <td><%= link_to 'Edit', edit_transaction_type_path(transaction_type) %></td>
        <td><%= link_to 'Destroy', transaction_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction type', new_transaction_type_path %>

app/views/transaction_types/new.html.erb
<h1>New transaction_type</h1>

<%= render 'form' %>

<%= link_to 'Back', transaction_types_path %>

app/views/transaction_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_type_path(@transaction_type) %> |
<%= link_to 'Back', transaction_types_path %>