config/routes.rb
Rails.application.routes.draw do
  resources :acct_types

  resources :acct_transactions

  resources :addresses

  get 'home/index'
  get 'home/about'
  root 'home#index'

  resources :account_types, :accounts, :administrators, :customers, :roles, :states, :transaction_types, :transactions, :users, :zip_codes

end

app/models/account.rb
class Account < ActiveRecord::Base
	# self.primary_key = "id"

	has_one :customer
	has_one :account_type
	has_many :acct_transactions
end

app/models/acct_transaction.rb
class AcctTransaction < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :account
	has_one :transaction_type
end

app/models/acct_type.rb
class AcctType < ActiveRecord::Base
	belongs_to :account
end

app/models/address.rb
class Address < ActiveRecord::Base
	# self.primary_key = "customer_id"
	
	belongs_to :customer
	has_one :zip_code
	has_one :state, through: :zip_code
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :user
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	# self.primary_key = "id"
	
	belongs_to :user
	has_one :address
	has_many :accounts
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :zip_code
end

app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
	belongs_to :transactions
end

app/models/user.rb
class User < ActiveRecord::Base
	# self.primary_key = "id"

	# has_one :role
	has_many :customers
	has_many :administrators
end

app/models/zip_code.rb
class ZipCode < ActiveRecord::Base
	# self.primary_key = "zip_code"
	
	has_one :state
	belongs_to :address
end

app/controllers/acct_transactions_controller.rb
class AcctTransactionsController < ApplicationController
  before_action :set_acct_transaction, only: [:show, :edit, :update, :destroy]

  # GET /acct_transactions
  # GET /acct_transactions.json
  def index
    @acct_transactions = AcctTransaction.all
  end

  # GET /acct_transactions/1
  # GET /acct_transactions/1.json
  def show
  end

  # GET /acct_transactions/new
  def new
    @acct_transaction = AcctTransaction.new
  end

  # GET /acct_transactions/1/edit
  def edit
  end

  # POST /acct_transactions
  # POST /acct_transactions.json
  def create
    @acct_transaction = AcctTransaction.new(acct_transaction_params)

    respond_to do |format|
      if @acct_transaction.save
        format.html { redirect_to @acct_transaction, notice: 'Acct transaction was successfully created.' }
        format.json { render :show, status: :created, location: @acct_transaction }
      else
        format.html { render :new }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acct_transactions/1
  # PATCH/PUT /acct_transactions/1.json
  def update
    respond_to do |format|
      if @acct_transaction.update(acct_transaction_params)
        format.html { redirect_to @acct_transaction, notice: 'Acct transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @acct_transaction }
      else
        format.html { render :edit }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acct_transactions/1
  # DELETE /acct_transactions/1.json
  def destroy
    @acct_transaction.destroy
    respond_to do |format|
      format.html { redirect_to acct_transactions_url, notice: 'Acct transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acct_transaction
      @acct_transaction = AcctTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acct_transaction_params
      params[:acct_transaction]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/acct_transactions_helper.rb
module AcctTransactionsHelper
end

app/helpers/acct_types_helper.rb
module AcctTypesHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

app/views/acct_transactions/_form.html.erb
<%= form_for(@acct_transaction) do |f| %>
  <% if @acct_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acct_transaction.errors.count, "error") %> prohibited this acct_transaction from being saved:</h2>

      <ul>
      <% @acct_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acct_transactions/edit.html.erb
<h1>Editing acct_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @acct_transaction %> |
<%= link_to 'Back', acct_transactions_path %>

app/views/acct_transactions/index.html.erb
<h1>Listing acct_transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acct_transactions.each do |acct_transaction| %>
      <tr>
        <td><%= link_to 'Show', acct_transaction %></td>
        <td><%= link_to 'Edit', edit_acct_transaction_path(acct_transaction) %></td>
        <td><%= link_to 'Destroy', acct_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acct transaction', new_acct_transaction_path %>

app/views/acct_transactions/new.html.erb
<h1>New acct_transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', acct_transactions_path %>

app/views/acct_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_acct_transaction_path(@acct_transaction) %> |
<%= link_to 'Back', acct_transactions_path %>